image: gitpod/workspace-full-vnc

tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y libglu1-mesa libxi-dev libxmu-dev
      docker-compose -f ./standalone/docker-compose.yml -f ./standalone-wordpress/docker-compose.yml pull
      docker-compose -f ./standalone/docker-compose.yml build
      docker-compose -f ./standalone-wordpress/docker-compose.yml build
      wget https://downloads.firestormviewer.org/linux/Phoenix-FirestormOS-Releasex64-6-6-14-69596.tar.xz -O ~/firestorm.tar.xz
      tar -xJf ~/firestorm.tar.xz -C ~
      sudo mkdir -p /opt/firestorm-install
      sudo mv ~/Phoenix-FirestormOS-Release*/* /opt/firestorm-install
      mkdir -p ~/.local/share/applications
      cp .gitpod/firestorm-viewer.desktop ~/.local/share/applications/firestorm-viewer.desktop
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    name: VNC Viewer
    onOpen: open-browser
