version: '3.6'
services:
  db:
    image: docker.io/library/mariadb:10.5
    volumes:
    - "database_store:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: metaverse
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 3
  db_pma:
    image: docker.io/library/phpmyadmin:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
    - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_USER: root
      PMA_PASSWORD: password
  metaverse:
    image: docker.io/soupbowl/opensimulator:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
    - "9000:9000"
    - "9000:9000/udp"
    environment:
      GRID_NAME: OpenSimulator Sandbox Standalone
      GRID_WELCOME: Running OpenSimulator in Standalone Grid mode.
      ESTATE_OWNER_NAME: Governor Linden
      ESTATE_OWNER_PASSWORD: password
      DATABASE_ENGINE: mysql
      MYSQL_SERVER: db
      MYSQL_DATABASE: metaverse
      MYSQL_USER: root
      MYSQL_PASSWORD: password
  www:
    image: nginx:latest
    volumes:
    - "./www:/usr/share/nginx/html:ro"
    ports:
    - 8080:80

volumes:
  database_store:
